spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhiyong-dev
    
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zhiyong-test
